chore: retrying release step with bash

diff --git a/.github/workflows/release.yml b/.github/workflows/release.yml
--- a/.github/workflows/release.yml
+++ b/.github/workflows/release.yml
@@ -50,8 +50,19 @@ jobs:
           JRELEASER_MAVENCENTRAL_PASSWORD: ${{ secrets.FLAMINGOCK_JRELEASER_MAVENCENTRAL_PASSWORD }}
 
       - name: Release to Maven Central portal
-        run: ./gradlew jreleaserFullRelease --no-daemon --stacktrace
-        retry: 5
+        run: |
+          for i in {1..3}; do
+            echo "\nRelease attempt $i"
+            if ./gradlew jreleaserFullRelease --no-daemon --stacktrace; then
+              exit 0
+            fi
+            if [ $i -eq 3 ]; then
+              echo "Failed release after 3 attempts"
+              exit 1
+            fi
+            echo "Retrying in 5 seconds"
+            sleep 5
+          done
         env:
           JRELEASER_GITHUB_TOKEN: ${{ secrets.FLAMINGOCK_JRELEASER_GITHUB_TOKEN }}
           JRELEASER_MAVENCENTRAL_USERNAME: ${{ secrets.FLAMINGOCK_JRELEASER_MAVENCENTRAL_USERNAME }}
