build: back to not using script

diff --git a/.github/workflows/release.yml b/.github/workflows/release.yml
--- a/.github/workflows/release.yml
+++ b/.github/workflows/release.yml
@@ -53,7 +53,18 @@ jobs:
 
       - name: Release core projects to Maven Central portal
         run: |
-          ./infra/portalCentralDeploy.sh core 5 20
+          for i in {1..3}; do
+            if ./gradlew jreleaserDeploy -PreleaseBundle=core --no-daemon --stacktrace; then
+              exit 0
+            fi
+            if [ $i -eq 3 ]; then
+              echo "Failed release after 3 attempts"
+              exit 1
+            fi
+            echo
+            echo "********************************************************************************** RELEASE ATTEMPT($((i + 1))) **********************************************************************************"
+            sleep 5
+          done
         env:
           JRELEASER_GITHUB_TOKEN: ${{ secrets.FLAMINGOCK_JRELEASER_GITHUB_TOKEN }}
           JRELEASER_MAVENCENTRAL_USERNAME: ${{ secrets.FLAMINGOCK_JRELEASER_MAVENCENTRAL_USERNAME }}
@@ -64,7 +75,18 @@ jobs:
 
       - name: Release driver projects to Maven Central portal
         run: |
-          ./infra/portalCentralDeploy.sh driver 5 20
+          for i in {1..3}; do
+            if ./gradlew jreleaserDeploy -PreleaseBundle=driver --no-daemon --stacktrace; then
+              exit 0
+            fi
+            if [ $i -eq 3 ]; then
+              echo "Failed release after 3 attempts"
+              exit 1
+            fi
+            echo
+            echo "********************************************************************************** RELEASE ATTEMPT($((i + 1))) **********************************************************************************"
+            sleep 5
+          done
         env:
           JRELEASER_GITHUB_TOKEN: ${{ secrets.FLAMINGOCK_JRELEASER_GITHUB_TOKEN }}
           JRELEASER_MAVENCENTRAL_USERNAME: ${{ secrets.FLAMINGOCK_JRELEASER_MAVENCENTRAL_USERNAME }}
@@ -75,7 +97,18 @@ jobs:
 
       - name: Release template projects to Maven Central portal
         run: |
-          ./infra/portalCentralDeploy.sh template 5 20
+          for i in {1..3}; do
+            if ./gradlew jreleaserDeploy -PreleaseBundle=template --no-daemon --stacktrace; then
+              exit 0
+            fi
+            if [ $i -eq 3 ]; then
+              echo "Failed release after 3 attempts"
+              exit 1
+            fi
+            echo
+            echo "********************************************************************************** RELEASE ATTEMPT($((i + 1))) **********************************************************************************"
+            sleep 5
+          done
         env:
           JRELEASER_GITHUB_TOKEN: ${{ secrets.FLAMINGOCK_JRELEASER_GITHUB_TOKEN }}
           JRELEASER_MAVENCENTRAL_USERNAME: ${{ secrets.FLAMINGOCK_JRELEASER_MAVENCENTRAL_USERNAME }}
@@ -86,7 +119,18 @@ jobs:
 
       - name: Release transactioner projects to Maven Central portal
         run: |
-          ./infra/portalCentralDeploy.sh transactioner 5 20
+          for i in {1..3}; do
+            if ./gradlew jreleaserDeploy -PreleaseBundle=transactioner --no-daemon --stacktrace; then
+              exit 0
+            fi
+            if [ $i -eq 3 ]; then
+              echo "Failed release after 3 attempts"
+              exit 1
+            fi
+            echo
+            echo "********************************************************************************** RELEASE ATTEMPT($((i + 1))) **********************************************************************************"
+            sleep 5
+          done
         env:
           JRELEASER_GITHUB_TOKEN: ${{ secrets.FLAMINGOCK_JRELEASER_GITHUB_TOKEN }}
           JRELEASER_MAVENCENTRAL_USERNAME: ${{ secrets.FLAMINGOCK_JRELEASER_MAVENCENTRAL_USERNAME }}
