chore: show git tags and nothing more

diff --git a/.github/workflows/release.yml b/.github/workflows/release.yml
--- a/.github/workflows/release.yml
+++ b/.github/workflows/release.yml
@@ -32,58 +32,59 @@ jobs:
         run: |
           git config user.email "actions@github.com"
           git config user.name "GitHub Actions"
+          git log --tags --simplify-by-decoration --pretty="format:%d - %cr"
 
-      - name: Set up GPG
-        run: |
-          echo "$GPG_SECRET_KEY" > private.asc
-          gpg --import --batch private.asc
-        env:
-          GPG_SECRET_KEY: ${{ secrets.FLAMINGOCK_JRELEASER_GPG_SECRET_KEY }}
-
-#      - name: Build, unit and Integration tests
-#        run: ./gradlew clean build
-
-      - name: Perform publish
-        run: ./gradlew publish
-        env:
-          JRELEASER_MAVENCENTRAL_USERNAME: ${{ secrets.FLAMINGOCK_JRELEASER_MAVENCENTRAL_USERNAME }}
-          JRELEASER_MAVENCENTRAL_PASSWORD: ${{ secrets.FLAMINGOCK_JRELEASER_MAVENCENTRAL_PASSWORD }}
-
-      - name: Release to Maven Central portal
-        run: |
-          for i in {1..3}; do
-            if ./gradlew jreleaserFullRelease --no-daemon --stacktrace; then
-              exit 0
-            fi
-            if [ $i -eq 3 ]; then
-              echo "Failed release after 3 attempts"
-              exit 1
-            fi
-            echo
-            echo "********************************************************************************** RELEASE ATTEMPT($((i + 1))) **********************************************************************************"
-            sleep 5
-          done
-        env:
-          JRELEASER_GITHUB_TOKEN: ${{ secrets.FLAMINGOCK_JRELEASER_GITHUB_TOKEN }}
-          JRELEASER_MAVENCENTRAL_USERNAME: ${{ secrets.FLAMINGOCK_JRELEASER_MAVENCENTRAL_USERNAME }}
-          JRELEASER_MAVENCENTRAL_PASSWORD: ${{ secrets.FLAMINGOCK_JRELEASER_MAVENCENTRAL_PASSWORD }}
-          JRELEASER_GPG_PUBLIC_KEY: ${{ secrets.FLAMINGOCK_JRELEASER_GPG_PUBLIC_KEY }}
-          JRELEASER_GPG_SECRET_KEY: ${{ secrets.FLAMINGOCK_JRELEASER_GPG_SECRET_KEY }}
-          JRELEASER_GPG_PASSPHRASE: ${{ secrets.FLAMINGOCK_JRELEASER_GPG_PASSPHRASE }}
-
-      - name: JReleaser release output
-        if: always()
-        uses: actions/upload-artifact@v4
-        with:
-          name: jreleaser-release
-          path: |
-            build/jreleaser/output.properties
-            build/jreleaser/trace.log
-
-
-#      - name: Synchronizing develop branch
+#      - name: Set up GPG
 #        run: |
-#          git pull origin
-#          git checkout develop
-#          git merge -X theirs master --allow-unrelated-histories
-#          git push origin develop
+#          echo "$GPG_SECRET_KEY" > private.asc
+#          gpg --import --batch private.asc
+#        env:
+#          GPG_SECRET_KEY: ${{ secrets.FLAMINGOCK_JRELEASER_GPG_SECRET_KEY }}
+#
+##      - name: Build, unit and Integration tests
+##        run: ./gradlew clean build
+#
+#      - name: Perform publish
+#        run: ./gradlew publish
+#        env:
+#          JRELEASER_MAVENCENTRAL_USERNAME: ${{ secrets.FLAMINGOCK_JRELEASER_MAVENCENTRAL_USERNAME }}
+#          JRELEASER_MAVENCENTRAL_PASSWORD: ${{ secrets.FLAMINGOCK_JRELEASER_MAVENCENTRAL_PASSWORD }}
+#
+#      - name: Release to Maven Central portal
+#        run: |
+#          for i in {1..3}; do
+#            if ./gradlew jreleaserFullRelease --no-daemon --stacktrace; then
+#              exit 0
+#            fi
+#            if [ $i -eq 3 ]; then
+#              echo "Failed release after 3 attempts"
+#              exit 1
+#            fi
+#            echo
+#            echo "********************************************************************************** RELEASE ATTEMPT($((i + 1))) **********************************************************************************"
+#            sleep 5
+#          done
+#        env:
+#          JRELEASER_GITHUB_TOKEN: ${{ secrets.FLAMINGOCK_JRELEASER_GITHUB_TOKEN }}
+#          JRELEASER_MAVENCENTRAL_USERNAME: ${{ secrets.FLAMINGOCK_JRELEASER_MAVENCENTRAL_USERNAME }}
+#          JRELEASER_MAVENCENTRAL_PASSWORD: ${{ secrets.FLAMINGOCK_JRELEASER_MAVENCENTRAL_PASSWORD }}
+#          JRELEASER_GPG_PUBLIC_KEY: ${{ secrets.FLAMINGOCK_JRELEASER_GPG_PUBLIC_KEY }}
+#          JRELEASER_GPG_SECRET_KEY: ${{ secrets.FLAMINGOCK_JRELEASER_GPG_SECRET_KEY }}
+#          JRELEASER_GPG_PASSPHRASE: ${{ secrets.FLAMINGOCK_JRELEASER_GPG_PASSPHRASE }}
+#
+#      - name: JReleaser release output
+#        if: always()
+#        uses: actions/upload-artifact@v4
+#        with:
+#          name: jreleaser-release
+#          path: |
+#            build/jreleaser/output.properties
+#            build/jreleaser/trace.log
+#
+#
+##      - name: Synchronizing develop branch
+##        run: |
+##          git pull origin
+##          git checkout develop
+##          git merge -X theirs master --allow-unrelated-histories
+##          git push origin develop
